# -*- coding: utf-8 -*-
"""SearChEngIne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOYsD6HrmtjoOzA-1ms1KXtnmkmBalN1
"""
"""
!pip install faiss-cpu
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
from tqdm import tqdm
import faiss
import numpy as np
from torch.optim import AdamW

MODEL_NAME = "bert-base-uncased"
MAX_LENGTH = 128
BATCH_SIZE = 16
EPOCHS = 3
LR = 2e-5
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

class BiEncoder(nn.Module):
    def __init__(self, model_name):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(model_name)

    def forward(self, input_ids, attention_mask):
        outputs = self.encoder(
            input_ids = input_ids,
            attention_mask = attention_mask
        )
        cls_embedding = outputs.last_hidden_state[:, 0]
        return cls_embedding

def tokenize(batch, tokenizer):
    return tokenizer(
        batch["query"],
        batch["positive_passages"]["passage_text"][0],
        padding = "max_length",
        truncation = True,
        max_length = MAX_LENGTH
    )

def prepare_dataset():
    dataset = load_dataset("ms_marco", "v2.1", split="train")
    dataset = dataset.select(range(100000))

    return dataset

def train():
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = BiEncoder(MODEL_NAME).to(DEVICE)

    dataset = prepare_dataset()

    def collate_fn(batch):
        queries = [x["query"] for x in batch]
        positive_passage_texts = []
        for x_item in batch:
            passage_texts = x_item["passages"]["passage_text"]
            is_selected_flags = x_item["passages"]["is_selected"]
            found_positive = False
            for i, is_selected in enumerate(is_selected_flags):
                if is_selected == 1:
                    positive_passage_texts.append(passage_texts[i])
                    found_positive = True
                    break
            if not found_positive:
                positive_passage_texts.append(passage_texts[0] if passage_texts else "")

        q_tokens = tokenizer(
            queries,
            padding = True,
            truncation = True,
            max_length = MAX_LENGTH,
            return_tensors = "pt"
        )

        p_tokens = tokenizer(
            positive_passage_texts, # Corrected to use extracted positive passages
            padding = True,
            truncation = True,
            max_length = MAX_LENGTH,
            return_tensors = "pt"
        )

        return q_tokens, p_tokens
    loader = DataLoader(dataset, batch_size = BATCH_SIZE, shuffle=True, collate_fn = collate_fn)

    optimizer = AdamW(model.parameters(), lr=LR)
    scaler = torch.cuda.amp.GradScaler()

    model.train()

    for epoch in range(EPOCHS):
        total_loss = 0
        loop = tqdm(loader)

        for q_tokens, p_tokens in loop:
            optimizer.zero_grad()

            q_input_ids = q_tokens["input_ids"].to(DEVICE)
            q_mask = q_tokens["attention_mask"].to(DEVICE)

            p_input_ids = p_tokens["input_ids"].to(DEVICE)
            p_mask = p_tokens["attention_mask"].to(DEVICE)

            with torch.cuda.amp.autocast():
                q_emb = model(q_input_ids, q_mask)
                p_emb = model(p_input_ids, p_mask)

                scores = torch.matmul(q_emb, p_emb.T)
                labels = torch.arange(scores.size(0)).to(DEVICE)

                loss = F.cross_entropy(scores, labels)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

            total_loss += loss.item()
            loop.set_description(f"Epoch {epoch+1}")
            loop.set_postfix(loss=loss.item())

        print(f"Epoch {epoch+1} Loss: {total_loss/len(loader)}")
    torch.save(model.state_dict(), "bi_encoder.pt")
    print("-----------Model Saved-----------")

def build_index(num_passages=200000, batch_size=64):
    print("Loading tokenizer and model...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    model = BiEncoder(MODEL_NAME).to(DEVICE)
    model.load_state_dict(torch.load("bi_encoder.pt", map_location=DEVICE))
    model.eval()

    print("Loading MS MARCO (streaming)...")
    dataset = load_dataset(
        "ms_marco",
        "v2.1",
        split="train",
        streaming=True
    )

    print(f"Collecting {num_passages} passages...")
    passages = []

    for item in dataset.take(num_passages):
        # Take first passage per query
        passages.append(item["passages"]["passage_text"][0])

    print("Encoding passages...")

    all_embeddings = []

    with torch.no_grad():
        for i in tqdm(range(0, len(passages), batch_size)):
            batch = passages[i:i+batch_size]

            tokens = tokenizer(
                batch,
                padding=True,
                truncation=True,
                max_length=MAX_LENGTH,
                return_tensors="pt"
            ).to(DEVICE)

            emb = model(tokens["input_ids"], tokens["attention_mask"])

            # Move to CPU immediately
            emb = emb.cpu().numpy()

            # Normalize for cosine similarity
            emb = emb / np.linalg.norm(emb, axis=1, keepdims=True)

            all_embeddings.append(emb)

    embeddings = np.vstack(all_embeddings).astype("float32")

    print("Building FAISS index (cosine similarity)...")

    dim = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(embeddings)

    faiss.write_index(index, "msmarco.index")

    np.save("passages.npy", np.array(passages, dtype=object))

    print("Index built and saved successfully.")

def search(query, top_k=5):
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = BiEncoder(MODEL_NAME).to(DEVICE)
    model.load_state_dict(torch.load("bi_encoder.pt", map_location=DEVICE))
    model.eval()

    # Load FAISS index
    index = faiss.read_index("msmarco.index")

    # Load saved passages
    passages = np.load("passages.npy", allow_pickle=True)

    # Tokenize query
    tokens = tokenizer(
        [query],
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        query_emb = model(tokens["input_ids"], tokens["attention_mask"])

    query_emb = query_emb.cpu().numpy()

    # Normalize query for cosine similarity
    query_emb = query_emb / np.linalg.norm(query_emb, axis=1, keepdims=True)

    # Search
    scores, indices = index.search(query_emb, top_k)

    print("\nQuery:", query)
    print("=" * 60)

    for rank, (score, idx) in enumerate(zip(scores[0], indices[0]), start=1):
        print(f"\nRank {rank}")
        print(f"Score (Cosine Similarity): {score:.4f}")
        print(f"Index: {idx}")
        print("Passage:")
        print(passages[idx])
        print("-" * 60)

    return scores, indices

if __name__ == "__main__":
    #train()
    #build_index()

    print(search("What is artificial intelligence?"))

